<<<<<<< HEAD
#ifndef PIN_CONFIG_H
#define PIN_CONFIG_H

#define DEFAULT_PZEM_RX_PIN 16
#define DEFAULT_PZEM_TX_PIN 17
#define DEFAULT_DHT_PIN 4
#define DEFAULT_DS18B20_PIN 5
#define DEFAULT_MLX_SDA_PIN 7
#define DEFAULT_MLX_SCL_PIN 8
#define DEFAULT_LCD_SDA_PIN 10
#define DEFAULT_LCD_SCL_PIN 11
#define DEFAULT_RTC_SDA_PIN 12
#define DEFAULT_RTC_SCL_PIN 13
#define DEFAULT_RELAY_PIN 36
#define DEFAULT_BTN_PIN 3
#define DEFAULT_BTN_RESTORE_PIN 38

=======
#ifndef PIN_CONFIG_H
#define PIN_CONFIG_H

#define DEFAULT_PZEM_RX_PIN 16
#define DEFAULT_PZEM_TX_PIN 17
#define DEFAULT_DHT_PIN 4
#define DEFAULT_DS18B20_PIN 5
#define DEFAULT_MLX_SDA_PIN 7
#define DEFAULT_MLX_SCL_PIN 8
#define DEFAULT_LCD_SDA_PIN 10
#define DEFAULT_LCD_SCL_PIN 11
#define DEFAULT_RTC_SDA_PIN 12
#define DEFAULT_RTC_SCL_PIN 13
#define DEFAULT_RELAY_PIN 36
#define DEFAULT_BTN_PIN 3
#define DEFAULT_BTN_RESTORE_PIN 38

>>>>>>> c33c85add95660613ecc968467e618cd78c9a62f
#endif